PREP(countItem);
PREP(getMissingGear);
PREP(getNightGear);
PREP(getSpecialGear);
PREP(handleDisplayClosed);
PREP(handleDisplayOpened);
PREP(handleLoadout);
PREP(handleLoadoutsDisplayClosed);
PREP(handleLoadoutsDisplayOpened);
