RENAME(milgp_bp_Breacher_aor1,"Back Panel Breacher (AOR1)");
RENAME(milgp_bp_Breacher_aor2,"Back Panel Breacher (AOR2)");
RENAME(milgp_bp_Breacher_blk,"Back Panel Breacher (BLK)");
RENAME(milgp_bp_Breacher_cb,"Back Panel Breacher (CB)");
RENAME(milgp_bp_Breacher_khk,"Back Panel Breacher (KHK)");
RENAME(milgp_bp_Breacher_mc,"Back Panel Breacher (MC)");
RENAME(milgp_bp_Breacher_mcar,"Back Panel Breacher (MCAR)");
RENAME(milgp_bp_Breacher_mcb,"Back Panel Breacher (MCB)");
RENAME(milgp_bp_Breacher_mct,"Back Panel Breacher (MCT)");
RENAME(milgp_bp_Breacher_rgr,"Back Panel Breacher (RGR)");
RENAME(milgp_bp_Breacher_tan,"Back Panel Breacher (TAN)");
RENAME(milgp_bp_Breacher_wht,"Back Panel Breacher (WHT)");
RENAME(milgp_bp_hydration_aor1,"Back Panel Hydration (AOR1)");
RENAME(milgp_bp_hydration_aor2,"Back Panel Hydration (AOR2)");
RENAME(milgp_bp_hydration_blk,"Back Panel Hydration (BLK)");
RENAME(milgp_bp_hydration_cb,"Back Panel Hydration (CB)");
RENAME(milgp_bp_hydration_khk,"Back Panel Hydration (KHK)");
RENAME(milgp_bp_hydration_mc,"Back Panel Hydration (MC)");
RENAME(milgp_bp_hydration_mcar,"Back Panel Hydration (MCAR)");
RENAME(milgp_bp_hydration_mcb,"Back Panel Hydration (MCB)");
RENAME(milgp_bp_hydration_mct,"Back Panel Hydration (MCT)");
RENAME(milgp_bp_hydration_rgr,"Back Panel Hydration (RGR)");
RENAME(milgp_bp_hydration_tan,"Back Panel Hydration (TAN)");
RENAME(milgp_bp_hydration_wht,"Back Panel Hydration (WHT)");
RENAME(milgp_bp_Pointman_aor1,"Back Panel Pointman (AOR1)");
RENAME(milgp_bp_Pointman_aor2,"Back Panel Pointman (AOR2)");
RENAME(milgp_bp_Pointman_blk,"Back Panel Pointman (BLK)");
RENAME(milgp_bp_Pointman_cb,"Back Panel Pointman (CB)");
RENAME(milgp_bp_Pointman_khk,"Back Panel Pointman (KHK)");
RENAME(milgp_bp_Pointman_mc,"Back Panel Pointman (MC)");
RENAME(milgp_bp_Pointman_mcar,"Back Panel Pointman (MCAR)");
RENAME(milgp_bp_Pointman_mcb,"Back Panel Pointman (MCB)");
RENAME(milgp_bp_Pointman_mct,"Back Panel Pointman (MCT)");
RENAME(milgp_bp_Pointman_rgr,"Back Panel Pointman (RGR)");
RENAME(milgp_bp_Pointman_tan,"Back Panel Pointman (TAN)");
RENAME(milgp_bp_Pointman_wht,"Back Panel Pointman (WHT)");
RENAME(milgp_bp_Tomahawk_aor1,"Back Panel Tomahawk (AOR1)");
RENAME(milgp_bp_Tomahawk_aor2,"Back Panel Tomahawk (AOR2)");
RENAME(milgp_bp_Tomahawk_blk,"Back Panel Tomahawk (BLK)");
RENAME(milgp_bp_Tomahawk_cb,"Back Panel Tomahawk (CB)");
RENAME(milgp_bp_Tomahawk_khk,"Back Panel Tomahawk (KHK)");
RENAME(milgp_bp_Tomahawk_mc,"Back Panel Tomahawk (MC)");
RENAME(milgp_bp_Tomahawk_mcar,"Back Panel Tomahawk (MCAR)");
RENAME(milgp_bp_Tomahawk_mcb,"Back Panel Tomahawk (MCB)");
RENAME(milgp_bp_Tomahawk_mct,"Back Panel Tomahawk (MCT)");
RENAME(milgp_bp_Tomahawk_rgr,"Back Panel Tomahawk (RGR)");
RENAME(milgp_bp_Tomahawk_tan,"Back Panel Tomahawk (TAN)");
RENAME(milgp_bp_Tomahawk_wht,"Back Panel Tomahawk (WHT)");
RENAME(milgp_b_patrol_01_aor1,"Patrol (AOR1)");
RENAME(milgp_b_patrol_01_aor2,"Patrol (AOR2)");
RENAME(milgp_b_patrol_01_blk,"Patrol (BLK)");
RENAME(milgp_b_patrol_01_cb,"Patrol (CB)");
RENAME(milgp_b_patrol_01_khk,"Patrol (KHK)");
RENAME(milgp_b_patrol_01_mc,"Patrol (MC)");
RENAME(milgp_b_patrol_01_mcar,"Patrol (MCAR)");
RENAME(milgp_b_patrol_01_mcb,"Patrol (MCB)");
RENAME(milgp_b_patrol_01_mct,"Patrol (MCT)");
RENAME(milgp_b_patrol_01_rgr,"Patrol (RGR)");
RENAME(milgp_b_patrol_01_tan,"Patrol (TAN)");
RENAME(milgp_b_patrol_01_wht,"Patrol (WHT)");
