name: arma

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1

      - uses: Swatinem/rust-cache@v1
        with:
          key: arma

      - name: Build Extension
        run: |
          cargo build --release
          cp target/release/synixe.dll synixe_x64.dll

      - name: Build Mod
        run: hemtt release --expsqfc

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: synixe.zip
          path: releases/synixe-latest.zip
